### ISSUE TITLE
# Centos 7 搭建是否需要用到「mysql」 or 「Mariadb」?

### ISSUE THREAD

**Issue by XuguojingCode** [jiangmitiao/cali#1]
![_20180406174707](https://user-images.githubusercontent.com/23274031/38414963-96f8e310-39c2-11e8-8c1a-d3850e5bfcb7.png)

**Comment by XuguojingCode** [comment]
已经创建了cali@localhost 的mariaDB用户,并授予全部权限,也提示权限问题...

**Comment by zhghg** [comment]
@XuguojingCode 确定是localhost还是127.0.0.1 两者并不一样
